config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, only: %i[create destroy]
  end
  
  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: {minimum: 5}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question!

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = "Answer created!"
      redirect_to question_path(@question)
    else
      @answers = Answer.order created_at: :desc
      render 'questions/show'
    end
  end

  def destroy
    answer = @question.answers.find params[:id]
    answer.destroy
    flash[:success] = "Answer deleted!"
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/concerns/pages_controller.rb
class PagesController <ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def show
    @answer = @question.answers.build
    @answers = Answer.order created_at: :desc
  end

  def destroy
    @question.destroy
    flash[:success] = "Question deleted!"
    redirect_to questions_path
  end

  def edit
  end

  def update
    if @question.update question_params
      flash[:success] = "Question updated!"
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = "Question created!"
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>AskIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Home', root_path, class: 'nav-link px-2 text-white' %></li>
            <li><%= link_to 'Questions', questions_path, class: 'nav-link px-2 text-white' %></li>
          </ul>
        </nav>
      </div>
    </header>

    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to AskIt!</h1>

&copy; @bodrovis <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<h1 class='mb-4'>Edit question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1 class="mb-4">Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg' %>
<% @questions.each do |question| %>
  <article class="card mt-3">
    <div class="card-body">
      <h4><%= question.title %></h2>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%= question.body %>
        </p>
      </section>

      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %> 
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
        data: {method: :delete, confirm: 'Are you sure?'} %>
    </div>
  </article>
<% end %>

app/views/questions/new.html.erb
<h1 class='mb-4'>New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<p class="lead my-3">
  <%= @question.body %>
</p>

<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %> 
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
  data: {method: :delete, confirm: 'Are you sure?'} %>

<hr class="my-3">

<h2>Write your answer</h2>

<%= render 'shared/errors', object: @answer %>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

<h2 class="mt-5">Answers</h2>

<% @answers.each do |answer| %>
  <article class="mb-3">
    <time datetime="<%= answer.formatted_created_at %>">
      <%= answer.formatted_created_at %>
    </time>

    <p>
      <%= answer.body %>
    </p>

    <%= link_to 'Delete', question_answer_path(@question, answer), class: 'btn btn-danger btn-xs',
      data: {method: :delete, confirm: "Are you sure?"} %>
  </article>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>